# "systemName" defines the name of the VxFlex OS system from which volumes will
# be provisioned.
# systemName: scaleio1

# "username" defines the VxFlex OS administrative user used to authenticate.
# username: admin

# "password" defines the VxFlex OS administrative password used to authenticate.
# password: ---

# "restGateway" defines the VxFlex OS REST API endpoint, with full URL, typically
# leveraging HTTPS.
# restGateway: https://123.0.0.1

# "storagePool" defines the VxFlex storage pool from which this driver will
# provision volumes.
# storagePool: sp

#"mdmIP" defines the MDM(s) the SDC's should register with on start, comma separated
mdmIP: 192.168.1.1

# "volumeNamePrefix" defines a string prepended to each volume created by the
# CSI driver.
volumeNamePrefix: vxvol

# "controllerCount" defines the number of VxFlex controller nodes to deploy to
# the Kubernetes release
controllerCount: 1

#Where is the drv_cfg binary on the host?  By default, /bin/emc, but might be /var/vcap/packages/scaleIO_kernel on PKS
scaleio-path-bin: /bin/emc

images:
  # "images.agent" defines the container images used for the agent container.
  agent: docker.io/spiegela/csi-vxflex-agent:0.2.1

  # "images.attacher" defines the container images used for the csi attacher
  # container.
  attacher: quay.io/k8scsi/csi-attacher:v0.2.0

  # "images.attacher" defines the container images used for the csi provisioner
  # container.
  provisioner: quay.io/k8scsi/csi-provisioner:v0.2.1

  # "images.attacher" defines the container images used for the csi registrar
  # container.
  registrar: quay.io/k8scsi/driver-registrar:v0.2.0

storageClass:
  # "storageClass.name" defines the name of the storage class to be defined.
  name: vxflex

  # "storageClass.isDefault" defines whether the storage class should be the
  # default.
  isDefault: "true"

  # "storageClass.reclaimPolicy" defines what will happen when a volume is
  # removed from the Kubernetes API. Valid values are "Retain" and "Delete".
  reclaimPolicy: Delete
