apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ required "Must supply a VxFlex OS administrative username." .Values.username | b64enc }}
  password: {{ required "Must supply a VxFlex OS administrative password." .Values.password | b64enc }}
